app/index.js
app/templates/service.js
model/index.js
service/index.js
service/templates/generic-service.js
service/templates/memory-service.js
service/templates/mongoose-service.js
service/templates/nedb-service.js
service/templates/sequelize-service.js

This are some tweaks for the generator like removing the versioning. Closes #13. I will add another PR which adds the service import automatically to the index file.

Generator tweaks

---

.gitignore
.npmignore
lib/transforms.js
package.json
test/transform.test.js

This pull request adds a utility library for JS transformations that we need in the generators so that we don't have to rely on brittle regular expressions.

Adding utility library for AST transformations

---

generators/model/templates/mongoose.js
generators/model/templates/sequelize.js
generators/service/index.js
lib/transform.js

The default Sequelize model had some weird constraints that weren't necessary. Closes https://github.com/feathersjs/feathers/issues/231

Fix Sequelize model

---

generators/app/index.js
generators/app/templates/config.default.json
generators/app/templates/config.production.json

making sure services and config are configured if local auth is the only option. Closes #55.

fixing when local auth is only auth

---

generators/app/index.js
generators/app/templates/authentication.js
generators/hook/templates/hook.js
generators/middleware/index.js
generators/service/templates/hooks.js

This should be the final tweaks for the generator. It
- Makes sure that the correct versions are installed. Before it was only installing 1.0, 2.0 etc. not the latest 1.x
- Always adds the remove password hook for clients
- Some small cosmetics and redundant code

Some more generator fixes for the release

---

generators/app/index.js
generators/middleware/index.js
generators/model/index.js

Fix last Object.assign references and package.json as props

---

.editorconfig
lib/transform.js
test/transform.test.js

It blew up before which wasn't very cool.
Closes #72

Allows AST transformations when there are comments.

---

generators/service/templates/generic-service.js
test/generators.test.js

Closes https://github.com/feathersjs/generator-feathers/issues/74 and closes https://github.com/feathersjs/feathers/issues/275

Add test and fix for generic service

---

generators/app/index.js
generators/model/index.js
generators/model/templates/mongoose.js
generators/model/templates/sequelize.js
generators/service/index.js

Closes #75. Closes #87. Models now work out of the box when using an OAuth provider.

fixing how models are generated. 

---

generators/app/templates/README.md

Promoting the use of feathers-cli instead of yo generators in generators/app/templates/README.md

Promoting the use of feathers-cli

---

lib/updateMixin.js

Added a bypass to the update notification for a better `feathers-cli` UX addressing feathersjs/feathers-cli#12

Added an option to bypass the update notification

---

generators/app/index.js
generators/app/templates/static/test/app.test.js
package.json
test/generators.test.js

Needs a patch release once passing. Closes #109, #104

Fix generated app tests for latest packages

---

lib/transform.js
test/transform.test.js

Closes https://github.com/feathersjs/feathers/issues/295

Fix AST transformation when there is another expression

---

generators/app/templates/README.md

Thanks for the awesome project! LMK if this is the right format for a PR/commit message.

Remove typo, update year in generated README

---

lib/transform.js
test/transform.test.js

Closes https://github.com/feathersjs/feathers-cli/issues/25

Test and fix for commented out hooks

---

generators/app/index.js

feathers-configuration 0.4.0

---

generators/authentication/index.js
generators/connection/index.js
generators/hook/index.js
generators/middleware/index.js
generators/service/index.js
lib/generator.js

Improved checks and error messages if the generator can run properly

---

generators/connection/index.js
generators/service/index.js
generators/service/templates/types/rethinkdb.js

Rethinkdb finalization

---

generators/app/templates/_gitignore

Closes https://github.com/feathersjs/generator-feathers/issues/184

ignore junk files

---

generators/app/configs/package.json.js
generators/service/templates/filters.js
generators/service/templates/hooks-user.js

Set name based on npm

---

generators/service/templates/model/nedb-user.js

Closes https://github.com/feathersjs/feathers-chat/pull/49

Add email unique index to NeDB user model

---

generators/connection/templates/sequelize-mssql.js

Fix Sequelize MSSQL client reference

---

generators/service/templates/test.js

Closes https://github.com/feathersjs/feathers-cli/issues/85

Use proper path to get service in test

---

generators/connection/templates/sequelize-mssql.js

Closes https://github.com/feathersjs/feathers-cli/issues/84

Split username and password from URL parsed auth

---

generators/app/configs/package.json.js
generators/app/index.js
generators/hook/index.js
generators/service/index.js
lib/generator.js

As discussed in https://github.com/feathersjs/generator-feathers/pull/209#issuecomment-297196183 and closes #209

Allow to customize the test directory

---

generators/service/templates/model/knex.js
package.json
yarn.lock

So that the tests of the generated app are being run automatically when its dependencies are updated.

Add all generated app dependencies as devDependencies

---

generators/service/templates/model/sequelize-user.js

The normal model was updated already in #216 but not the user model.
Closes #224

Update user model to Sequelize 4

---

generators/connection/index.js

Closes https://github.com/feathersjs/feathers/issues/577

Fix use of both MongoDB and Mongoose in the same app

---

generators/app/templates/src/middleware/index.js
generators/middleware/index.js
generators/service/index.js
generators/service/templates/model/mongoose.js
lib/transform.js
test/generators.test.js
test/transform.test.js

This simplifies generating a middleware and makes the code transformation the same as adding a service adding an `insertLastInFunction` code transformation.
Closes #228

Fix and simplify generating a middleware

---

generators/service/templates/model/knex.js

Closes https://github.com/feathersjs/feathers/issues/581

Use Knex createTable workaround

---

generators/app/templates/app.js

Argument is no longer in use. Fixes #234.

Remove path argument from configuration

---

generators/authentication/index.js

Closes https://github.com/feathersjs/generator-feathers/issues/236

Remove wrong entity name from local authentication configuration

---

generators/service/templates/model/sequelize-user.js
generators/service/templates/model/sequelize.js

Closes https://github.com/feathersjs/feathers-sequelize/issues/118

Also set raw to true in beforeCount hook

---

generators/connection/index.js
package-lock.json

Fix for the postgres connection issue. Looks like it would impact more than just postgres from what i can see though.
Reference on feathers-cli#100
> Can not create service on postgres if default.json already has the connection string #100
[Link to issue](https://github.com/feathersjs/feathers-cli/issues/100)

Postgres connection fix

---

generators/connection/index.js

rethinkdb stores an object for connections

Fix problem with rethinkdb

---

generators/authentication/index.js

Closes https://github.com/feathersjs/feathers-docs/issues/612

Enable local authentication by default for auth generator

---

generators/connection/templates/mongoose.js

Closes https://github.com/feathersjs/feathers-generator/issues/67

Update connection code for latest MongoDB

---

generators/connection/index.js

fix(knex): Fix knex + sql server issues

---

generators/service/templates/model/sequelize-user.js
generators/service/templates/model/sequelize.js

access to types from DataTypes
(help webstorm autocomplete types of sequelize)

change template of default models for sequelize

---

generators/connection/index.js
package-lock.json

Properly handle connection string for Knex SQLite

---

generators/authentication/templates/authentication.js

Edit file so that `app.configure(jwt(config.jwt))` and `app.configure(local(config.local))` are consistent.

Strategy configuration consistency

---

generators/app/index.js

Filter into valid project name

---

generators/authentication/templates/authentication.js

Follow up on #276
- Closes https://github.com/feathersjs/generator-feathers/issues/278
- Closes https://github.com/feathersjs/feathers-docs/issues/837
- Closes https://github.com/feathersjs/feathers-authentication-jwt/issues/35

Fix authentication configuration

---

generators/service/templates/model/mongoose-user.js
generators/service/templates/model/mongoose.js

No test case added, hope it's fine for a template file -_-

Tweak the `timestamp` in mongoose model template

---

generators/service/templates/model/knex.js

it will easily fix wrong generated table name.

update knex model to use tableName const

---

generators/service/templates/model/sequelize-user.js
generators/service/templates/model/sequelize.js

Follow-up on #289. Closes https://github.com/feathersjs/generator-feathers/issues/291

Use snake_name for Sequelize table name as well

---

lib/generator.js
package.json

Closes #292, references #242 and a whole bunch of other issues.

Do not reinstall existing dependencies

---

generators/connection/index.js

Install mssql instead of tedious

---

generators/app/templates/app.js

This should make it much clearer where what lives. Everything Express related is now in `@feathersjs/express`.

Update for finalized Express bindings

---

.eslintrc.json
generators/app/configs/package.json.js
generators/app/templates/static/.eslintrc.json
generators/hook/index.js
generators/hook/templates/hook-async.js
generators/service/index.js
generators/service/templates/class-async.js
lib/generator.js
package-lock.json
package.json
test/generators.test.js

This will generate hooks and service methods `async` if your Node version and the `engines.node` range in `package.json` indicate that v8 or later is supported.

Use async/await for generated hooks and custom services if available

---

generators/connection/templates/mongodb.js

API changes in 3.0 cause this to break. Everything else seems to work flawlessly.
https://github.com/mongodb/node-mongodb-native/blob/3.0.0/CHANGES_3.0.0.md#api-changes

mongodb 3.0.0-rc0 support

---

lib/generator.js
package-lock.json
package.json

Closes https://github.com/feathersjs/generator-feathers/issues/308

Log error if trying to use the generator with incompatible versions

---

generators/app/templates/src/channels.js

changed the user param to authResult which is more accurate.
Added a user variable from connection to allow the example to function in its entirety.
Added a check to "Array.IsArray" to the user.rooms to ensure it both exists and is an array.
Added another example of channel sorting for specified users via email and id
Placed a NOT RECOMMENDED comment after the app.publish for all authenticated users
Added a new publish method to demonstrate how a messages service would utilize the emails and ids to send to users involved.

add features and fix typos

---

generators/hook/index.js
generators/hook/templates/test-async.js
generators/service/templates/hooks-user.js
test/generators.test.js

Change hook tests to use an actual Feathers app

---

generators/connection/index.js
test/generators.test.js

Closes https://github.com/feathersjs/feathers/issues/748

Remove MariaDB since it will just use MySQL

---

generators/app/templates/src/channels.js

Because it appears that nobody actually reads the docs.

Publish to authenticated users by default

---

generators/connection/templates/sequelize-mssql.js
generators/connection/templates/sequelize.js

Add Sequelize operator aliases

---

generators/app/templates/src/channels.js
generators/app/templates/src/middleware/index.js
generators/app/templates/src/services/index.js
generators/hook/templates/hook-async.js
generators/service/templates/model/sequelize-user.js
generators/service/templates/model/sequelize.js

Change ESLint flag to make formatting easier

---

generators/authentication/index.js
package-lock.json

For some reason the composed generator is force overwriting the users service content so we will skip generating it if it already exists.
Also should close #249

Do not generate the users service if it already exists

---

generators/connection/templates/rethinkdb.js

Closes https://github.com/feathersjs/authentication-client/issues/89, closes https://github.com/feathersjs/feathers/issues/817

Fix RethinkDB setup

---

generators/connection/index.js

Closes https://github.com/feathersjs/cli/issues/142, closes https://github.com/feathersjs/generator-feathers/issues/343

Fix summary for generated connection

---

generators/service/templates/class-async.js
generators/service/templates/class.js
generators/service/templates/service.js
generators/service/templates/types/knex.js

Closes https://github.com/feathersjs-ecosystem/feathers-knex/issues/150

Remove confusing and unnecessary name parameter

---

generators/app/templates/README.md

That’s it for now.
Would be awesome to generate this via JS and pass it to the template. But I don’t have time for that right now.

Update copyright year in README template

---

generators/hook/index.js
package-lock.json

Closes #355, closes https://github.com/feathersjs/feathers/issues/871

Make service selection when generating a hook mandatory

---

generators/app/templates/src/hooks/log.js
generators/authentication/index.js

- Closes https://github.com/feathersjs/generator-feathers/issues/364
- Closes https://github.com/feathersjs/feathers/issues/887

Only log error stacks and add Auth0 scope

---

generators/app/index.js
generators/authentication/index.js
package-lock.json

Closes #369 also fixes a typo from #367

Force installation of Winston 3

---

generators/app/index.js

Adds 'ws' package if 'primus' is selected

---

generators/app/configs/package.json.js
generators/app/index.js

Tested locally:
- `npm i feathers-cli`
- `npm link generator-feathers`
- `npx feathers generate app`
- `npm run dev`
- `touch package.json`
Resolves #385

Add a dev script with nodemon as a watcher (#385)

---

generators/app/templates/README.md

Remove reference to model generator from README.md template (#387)

---

README.md
package-lock.json
package.json

From generator-feathers-ts to generator-feathers again

Revert back name to generator-feathers

---

generators/app/templates/ts/src/declarations.d.ts
generators/connection/index.js
generators/connection/templates/ts/sequelize.ts
generators/service/templates/ts/model/sequelize-user.ts
generators/service/templates/ts/model/sequelize.ts

- Set explicitly "any" type workaround (until we have better understanding for sequelize typings) for sequelize related files that prevent TS compiling
- Add @types/validate to devDependencies

Fix typescript generator related files for sequelize

---

generators/app/templates/ts/src/declarations.d.ts
generators/service/templates/ts/model/objection-user.ts
generators/service/templates/ts/model/objection.ts

fix typings in objection Model, make sure tsc compiles after files generated

Fix ts typings for generated objection model

---

generators/authentication/index.js
generators/service/templates/js/hooks-user.js
package.json

Closes https://github.com/feathersjs/feathers/issues/1404

Fix generate authentication

---

generators/app/configs/tsconfig.json.js
generators/authentication/templates/ts/authentication.ts
generators/service/index.js
generators/service/templates/js/service.js
generators/service/templates/js/types/cassandra.js
generators/service/templates/js/types/generic.js
generators/service/templates/js/types/knex.js
generators/service/templates/js/types/memory.js
generators/service/templates/js/types/mongodb.js
generators/service/templates/js/types/mongoose.js
generators/service/templates/js/types/nedb.js
generators/service/templates/js/types/objection.js
generators/service/templates/js/types/sequelize.js
generators/service/templates/ts/service.ts
generators/service/templates/ts/types/cassandra.ts
generators/service/templates/ts/types/generic.ts
generators/service/templates/ts/types/knex.ts
generators/service/templates/ts/types/memory.ts
generators/service/templates/ts/types/mongodb.ts
generators/service/templates/ts/types/mongoose.ts
generators/service/templates/ts/types/nedb.ts
generators/service/templates/ts/types/objection.ts
generators/service/templates/ts/types/sequelize.ts
test/generators.test.js

This will make things more consistent, easier to type and sets everything up for the upcoming new hook system.

Generate extended classes for every adapter type

---

generators/app/configs/package.json.js

Closes https://github.com/feathersjs/cli/issues/172

Remove unnecessary test script environment variable

---

generators/service/templates/ts/types/knex.ts

`const { Service, KnexServiceOptions } = require('feathers-knex');` prevent ts compile

Fix import in types/knex.ts

---

generators/service/templates/js/model/mongoose.js

Closes https://github.com/feathersjs/cli/issues/173

Handle Mongoose model intitialization errors

---

generators/app/configs/package.json.js
generators/app/templates/ts/src/declarations.d.ts
generators/connection/templates/ts/mongodb.ts
generators/service/index.js
generators/service/templates/ts/types/mongodb.ts
package-lock.json
package.json
test/generators.test.js

Add compile step to TS tests

---

generators/upgrade/index.js

Closes https://github.com/feathersjs/feathers/issues/1541

Handle special cases in the upgrade generator

---

generators/service/templates/ts/types/objection.ts

Should fix [this issue](https://github.com/feathersjs-ecosystem/feathers-objection/issues/60).

Fix Application import in objection service

---

generators/authentication/templates/ts/test.jest.ts
generators/authentication/templates/ts/test.mocha.ts

Will also be improved later with better typings. For now closes https://github.com/feathersjs/cli/issues/187 though

Fix type error in authentication tests

---

generators/app/configs/config.default.json.js
generators/connection/index.js
generators/hook/index.js
generators/middleware/index.js
generators/service/index.js
generators/upgrade/index.js

Closes https://github.com/feathersjs/generator-feathers/issues/470

Change all references of language checks to not rely on config files

---

generators/service/templates/js/types/generic.js

Fix eslint complaining about missing semi immediately after generation of generic service

Add missing semi

---

generators/service/templates/js/service.js
generators/service/templates/ts/service.ts

Closes https://github.com/feathersjs/cli/issues/195

Initialize service model and pagination in a single object

---

generators/app/index.js
generators/app/templates/ts/src/channels.ts
generators/app/templates/ts/src/declarations.d.ts

Closes https://github.com/feathersjs/feathers/issues/1652
Closes https://github.com/feathersjs/feathers/issues/1653

Move transport-commons and remove unnecessary imports

---

generators/connection/templates/js/mongodb.js
generators/connection/templates/ts/mongodb.ts

Closes https://github.com/feathersjs/generator-feathers/issues/480

Update MongoDB intialization

---

generators/app/index.js

minor typo

---

generators/app/templates/js/src/channels.js

see https://github.com/feathersjs/docs/blob/master/api/channels.md

Fixed typo and variable name in comments

---

generators/app/templates/ts/src/channels.ts

see https://github.com/feathersjs/docs/blob/master/api/channels.md

Fixed typo and wrong variable in comments

---

generators/authentication/index.js

Fixes #538 for `feathers generate app`

Fix remaining static 'users' entity

---

generators/app/templates/ts/app.ts
generators/app/templates/ts/src/channels.ts
generators/service/templates/ts/model/knex-user.ts
generators/service/templates/ts/model/knex.ts
generators/service/templates/ts/model/mongoose-user.ts
generators/service/templates/ts/model/mongoose.ts

Fix some typo in comments for typescript template files

fix: file extension typo

---

generators/app/templates/js/app.js
generators/app/templates/ts/app.ts

Closes https://github.com/feathersjs/feathers-chat/issues/147

Fix helmet content security policy configuration

---

generators/authentication/index.js

It's pretty common to want this so we can add it as suggested by @edwardsmarkf.

Update Auth0 default scope to include email

---

generators/app/configs/package.json.js
generators/app/index.js
generators/app/templates/ts/app.test.jest.ts
generators/app/templates/ts/app.test.mocha.ts

Should close https://github.com/feathersjs/generator-feathers/issues/644

Fix TypeScript issues when generating a new app

---

generators/app/index.js
package-lock.json
package.json

Closes https://github.com/feathersjs/cli/issues/285
Closes https://github.com/feathersjs/feathers/issues/2525

Lock colors dependency for fix broken command line
