feathersjs/generator-feathers

app/index.js
service/index.js

making sure that we explicitly set that choose your own db maps to "generic". Closes #16.

Fixing error "choosing your own db"

---

generators/app/templates/service.js

according to sequelize docs, mssql accepts a connection string just like mysql/pg
http://docs.sequelizejs.com/en/latest/docs/getting-started/#setting-up-a-connection
for instance, the generator does generate the connection string under config/default.json
```
"mssql": "mssql://root:@localhost:1433/test",
```
but it's not being used anywhere since it was being hard coded under /src/services/index.js

mssql to make use of config/*.json connection string

---

generators/app/index.js
generators/hook/index.js
generators/middleware/index.js
generators/model/index.js
generators/service/index.js
lib/updateMixin.js
package.json

So here's an attempt at fixing #63. It uses `[update-notifier](https://github.com/yeoman/update-notifier)` which pretty much every CLI tool uses for this sort of thing.
Here's what it looks like:
If there is an update, the user gets a prompt where they have 3 choices:
- they can have us invoke the command to install the update
- they can decline and continue with the generator
- they can exit the process
By default `update-notifier` will run at most weekly.

Addng an update prompt when any generators are invoked

---

lib/updateMixin.js

I just noticed that I left a `--dry-run` flag in the update script. This removes that so the script actually updates the generator.

Removing the dry-run arg so the update script actually updates

---

generators/app/templates/authentication.js

I did:
```bash
npm i -g yo generator-feathers
yo feathers
```
With settings:
```
? Project name feathers-ng2
? Description
? What type of API are you making? REST, Realtime via Socket.io
? CORS configuration Enabled for all domains
? What database do you primarily want to use? NeDB
? What authentication providers would you like to support? local, github
```
And `npm test` fails with:
```bash
> feathers-ng2@0.0.0 jshint /Users/avweiss/dev/feathers-ng2
> jshint src/. test/. --config
src/services/authentication/index.js: line 18, col 2, Missing semicolon.
```

jslint error in authentication

---

generators/app/index.js

By default the generator assumes postgres, root, etc. in the connection URL. This is probably fine but running `npm start` will fail. This commit simply tells users to verify the info and the general location to look for it.

Log slightly more helpful database information

---

generators/app/templates/config.default.json
generators/app/templates/config.production.json
test/generators.test.js

This pull request allows an empty CORS whitelist and also removes the duplication from `production.json`.
Closes #85

Allow empty CORS whitelist

---

generators/service/index.js
lib/transform.js
test/transform.test.js

This is my first PR to a popular open source project, which is awesome. But if I screwed something up please let me know :-)
There wasn't a test for the complete `importService()` function.  Nor did I see an obvious place to put one. So instead I added a test for `addImport()`, and fixed that so the varName handles hyphenated-names.  This seems right to me since I don't think hyphenated-names would be OK in any use of `addImport()`
But importService(), has another instance of the same problem.  I added the fix there as well, but did NOT add a case that covers that. Not sure where to put that.  However all tests do pass!.
comments?  is this ok?
Closes https://github.com/feathersjs/feathers-cli/issues/19

Allow hyphenated-names in services - fixes #113

---

README.md
generators/app/templates/static/test/app.test.js
generators/hook/templates/hook.test.js
generators/service/templates/index.test.js
test/generators.test.js

This PR addresses an issue I had trying to increase the timeout of a test, which wouldn't work due to the generated test passing arrow functions to mocha. From mocha docs:
>Passing arrow functions to Mocha is discouraged. Their lexical binding of the this value makes them unable to access the Mocha context, and statements like this.timeout(1000); will not work inside an arrow function.
[https://mochajs.org/#arrow-functions](https://mochajs.org/#arrow-functions).
I did not replace every arrow function in the test templates, as some of them seemed like they would never cause any issues. Also added notes to the README describing how to make changes to and test the generators via `npm link` (many people will likely already know this, I did not.)

Pass fewer arrow functions to Mocha. feathersjs/feathers#297

---

generators/app/templates/service.js
generators/model/templates/sequelize.js

Not sure how you feel about this, but it seems very redundant to me having `freezeTableName: true` appear in every single model when it could just be set in the Sequelize connection constructor call.

Move freezeTableName so it doesn't need to be set on every model.

---

generators/app/index.js
generators/app/templates/app.js
generators/authentication/index.js
generators/connection/index.js
generators/connection/templates/knex.js
generators/connection/templates/mongoose.js
generators/connection/templates/sequelize-mssql.js
generators/connection/templates/sequelize.js
generators/secret/index.js
generators/service/index.js
generators/service/templates/filters.js
generators/service/templates/hooks-user.js
generators/service/templates/hooks.js
generators/service/templates/model/mongoose-user.js
generators/service/templates/model/sequelize-user.js
generators/service/templates/service.js
lib/transform.js
test/generators.test.js
yarn.lock

This PR:
- Fixes an issue with socket.io
- Adds a "secret" generator to make it easier to generate new secrets from the CLI
- Adds support for more databases

Generator refactoring2

---

generators/authentication/index.js

For #138.
`profileFields` is needed for Facebook authentication to fetch user data.

Add profileFields for Facebook authentication

---

generators/connection/index.js

Fix RethinkDB generation

---

generators/connection/index.js

Prevent overwriting RethinkDB connection details by re-using existing
configuration settings.
Default to a valid RethinkDB database name.
closes #174 and #173

Suggest valid RethinkDB database name and prevent overwriting configuration settings

---

generators/authentication/templates/authentication.js

It makes more sense to have a successRedirect by default.  This way the user doesn’t see naked JSON in the auth response.

Add a successRedirect by default

---

generators/connection/index.js
generators/service/index.js

Currently, every time you generate a service the connection generator will force overwrite its connection file. This pull request fixes that.

Do not overwrite connection files when generating a service

---

generators/service/templates/model/sequelize.js

`classMethods` is deprecated as of 4.0.0
See http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html

Generate sequelize model according to sequelize 4.0

---

generators/app/templates/app.js
generators/app/templates/src/middleware/index.js

Generated middleware was only registered at the end (after all services). This means that it never got hit for service calls (e.g. not allowing to add things to `params`). It makes more sense to register the middleware before services and adding the `notFound` and error handler in the main `app.js`.
Closes #221

Improve order of generated middleware

---

generators/app/templates/static/public/index.html

- Link to https docs
- Use `title` instead of `alt` on the link to the docs

Minor changes to the generated index.html

---

generators/connection/index.js

Broken pg@7 support has been fixed via https://github.com/sequelize/sequelize/pull/7888
Closes https://github.com/feathersjs/generator-feathers/issues/246 and closes https://github.com/feathersjs/generator-feathers/issues/259

Use latest pg driver again

---

generators/app/templates/src/index.js

It's still better without, is not it ?
Allows to use the power of winston with `string interpolation`

Remove template strings in index.js

---

generators/app/templates/src/index.js

Holding Mod and hovering over the message doesn't allow you to click to open a tab. Frustrating on iTerm.

make default message clickable on iTerm

---

generators/app/configs/package.json.js

I think we want `yarn` if the user selected it as the package manager.

Use the selected packager to run commands

---

generators/service/index.js

Hello!
This is related to https://github.com/feathersjs/generator-feathers/issues/304. I encountered the same problem, because I'm using an arrow function instead of plain old function declaration.
I made the code print a message instead of throwing if it wasn't able to find the main function, so you just have to copy the line manually. It look like this:
I am then able to use the generators even if my`services/index.js` is modified.

Do not fail when the services index has been modified

---

generators/app/templates/app.js

Using the cors middleware after the helmet middleware allows helmet to secure OPTIONS requests. See https://github.com/helmetjs/helmet/issues/157.

Use cors after helmet

---

generators/app/templates/src/channels.js

Fixed comment typo on line 51 in `/generators/app/templates/src/channels.js`
Before: `// e..g`
After: `// e.g.`

Fixed comment typo on line 51

---

generators/hook/index.js
generators/service/index.js
generators/service/templates/service.js
generators/service/templates/test.js
generators/service/templates/types/knex.js
package-lock.json
package.json

This allows to generate services with names in nested folders like `blog/posts` or `v1/dashboard`.
Closes #341, closes #342

Allow generating services in nested folders

---

generators/service/index.js

My team has really enjoyed the recently added ability to generate services in nested folders via the CLI. One gotcha is that when generating a service that includes route parameters (i.e. `/users/:id/roles`) the route parameters are included in the directory hierarchy:
```
users
|___ :id
|___ roles
```
This pull request simply filters out any path part the begins with the ':' character, resulting in the following:
```
users
|___ roles
```

Exclude route parameters when generating services in nested folders

---

generators/app/templates/src/hooks/log.js

Elsewhere including this file there is no space e.g. "if(" i.e. between "if" and opening parenthesis

Remove space for consistent formatting

---

generators/authentication/index.js
generators/connection/index.js
generators/hook/index.js
generators/middleware/index.js
generators/service/index.js
package-lock.json
package.json

This is supposed to fix https://github.com/feathersjs/cli/issues/160
The default snake/camel/kebab case transformation is a problem if you wanna have something like `prefix.some-name` as the dot gets always transformed.
This PR fixes this, so you've got more freedom regarding the naming convention.
(Note: I didn't touch the authentication generator because I'm not sure if a dot may be a problem here)
@daffl @eddyystop is this adjustment ok for you?

Fix renaming to preserve dot notation

---

generators/connection/templates/mongoose.js

Currently it issues the following warning:
(node:6686) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.

Use new url parser

---

generators/app/index.js

A [critical security issue](https://www.npmjs.com/advisories/737) with [`flatmap-stream`](https://www.npmjs.com/package/flatmap-stream) was [traced to a sub-debpendency of `nodemon`](https://github.com/remy/nodemon/issues/1451). This is [fixed in `nodemon@1.18.7`](https://github.com/remy/nodemon/releases/tag/v1.18.7). I realize that `nodemon` is only a `devDependency` that is installed when you `feathers generate app` so it shouldn't affect production apps, and that since no version is currently specified it **_should_** get the latest version (which is fixed). However, I just updated my global `@feathersjs/cli` and ran `feathers generate app` and it installed `nodemon@1.18.6` which still contained the vulnerability.
For the time being, it seems wise to specify `nodemon@^1.18.7` in the …

Security update: ensure nodemon^1.18.7

---

generators/app/index.js
generators/app/templates/ts/app.interface.ts
generators/app/templates/ts/src/declarations.d.ts
generators/connection/templates/ts/cassandra.ts
generators/service/templates/ts/model/cassandra-user.ts
generators/service/templates/ts/model/cassandra.ts

- update src/declarations.d.ts for cassandra related npm modules
- set "any" type workaround to make app runnable without type errors after generated

Fix ts typings for cassandra

---

generators/app/templates/js/app.test.mocha.js
generators/app/templates/js/static/public/index.html

I accidentally ran Lighthouse against the index and was suggested to add `lang="en"` to increase the accessibility score, results shown below. If this is accepted I might take a look at the other suggestions as well.

Bumps lighthouse accessibility score

---

generators/hook/index.js

A fix for a bug where application-wide hook is written to app.hook.ts.* instead of app.hook.*

Fix duplicate extension for app hook generator

---

generators/app/templates/js/_gitignore

This file should be git-ignored as it is intended for (and may contain) user specific settings. For example, VSCode extensions usually store user-preferences in this file so we don't want to commit them to the repository.
Since we are not distributing the `settings.json` file with the generator this change should be harmless but will improve the user experience for VSCode users (not being surprised by `.vscode`  entries appearing in their git status).

Start git-ignoring .vscode/settings.json

---

generators/app/index.js

without version string, _packagerInstall in lib/generator.js will always use npm though yarn selected, because there is no entry in package.json engines field (version undefined)

Add packager version in choices value

---

generators/app/configs/config.test.json.js
generators/app/configs/index.js
generators/app/index.js

without NODE_ENV=, tested codes (config) will search for config/test.json because jest will provide NODE_ENV=test by default

fix: create test.json when generate app

---

generators/app/configs/package.json.js
lib/generator.js

Add the information if TypeScript is used into the `package.json` instead of using the configuration. Should also still be backwards compatible.
- Closes https://github.com/feathersjs/generator-feathers/issues/470
- Closes https://github.com/feathersjs/cli/issues/190

Use package.json to dettermine language

---

generators/app/templates/js/app.test.jest.js
generators/app/templates/js/app.test.mocha.js
generators/app/templates/js/src/index.js
generators/app/templates/ts/app.test.jest.ts
generators/app/templates/ts/app.test.mocha.ts
generators/app/templates/ts/src/index.ts

By default the app listens on all available interfaces, ignoring the configured hostname

Fixes app ignoring configured hostname

---

generators/service/templates/js/model/mongoose-user.js
generators/service/templates/js/model/mongoose.js
generators/service/templates/ts/model/mongoose-user.ts
generators/service/templates/ts/model/mongoose.ts

The generator for mongoose-user had not been updated to match the change
made for other mongoose services to avoid schema compilation errors in
watch mode for tests. This brings them in to line and also uses the method
recommended in the mongoose docs to deal with this situation.

Update mogoose generators

---

generators/service/templates/ts/types/mongodb.ts

The Typescript service generator for MongoDB had 'users' hard-coded for the collection name. I changed it to match the JS generator, using the service's kebabName.

Replaced string 'user' with the service name for mongoDB collection

---

generators/app/templates/js/app.test.jest.js
generators/app/templates/js/app.test.mocha.js
generators/app/templates/js/src/index.js
generators/app/templates/ts/app.test.jest.ts
generators/app/templates/ts/app.test.mocha.ts
generators/app/templates/ts/src/index.ts

This reverts #495 for now because there were many follow-up issues with generated applications not listening on Docker containers (e.g. [here](https://stackoverflow.com/questions/59309125/node-docker-not-working-for-feathersjs-container-running-but-localhost-not-acc)) or cloud deployments (e.g. Azuer).

Revert "Fixes app not listening to configured hostname (#495)"

---

generators/app/configs/package.json.js

yarn is showing much of this warning when generating app:
`warning package.json: No license field`
we can to set private field true in package.json to prevent the warnings

fix: set private field true in package.json

---

generators/app/templates/js/app.test.mocha.js
generators/authentication/templates/js/authentication.js
generators/service/templates/js/model/sequelize-user.js

Following #524 this fixes some lint errors I picked up by generating the project with StandardJS. I did this in a separate PR since #524 may undergo a longer review, while these fixes have no dependency on that PR and are just simple fixes.

Fix lint errors picked up by StandardJS

---

generators/app/configs/package.json.js
generators/app/index.js

Add prompt to choose linter between ESLint and StandardJS.
After installing dependencies, run the `lint` script just to use Standard's amazing auto-formater. That way no change is needed on the generated files.
It's my first time using Yeoman. Feedback is appreciated.

Add prompt to choose linter between ESLint and StandardJS

---

generators/app/templates/ts/app.ts

This helps with autocompleting the application
in your hooks you can do:
```TypeScript
(context: HookContext<User>) => {
context.app.service('..
users
notifications
roles
}
```
So when you start typing it will give autocomplete based on `declarations.ts`
Though it would be recommended to add HookContext
In my app i added the HookContext in the import blacklist tslint rule like so:
```
"import-blacklist": [
true,
{ "@feathersjs/feathers": ["HookContext"] }
],
```
So you can only import hookContext of YOUR app and not the default one

Export Application based hookcontext for autocompletion of services

---

generators/connection/index.js

Add missing 'mongodb' choice to connection prompt (db) (fixes #499)

---

generators/connection/templates/js/mongoose.js
generators/connection/templates/ts/mongoose.ts

Mongoose 5 (onwards) uses native promises by default, so no longer need to default `mongoose.Promise`, see https://masteringjs.io/tutorials/mongoose/promise

chore: remove mongoose.Promise

---

generators/app/index.js

Helmet does not need types anymore. The package is deprecated see https://www.npmjs.com/package/@types/helmet.
This change will also remove the warning when using ```feathers g app```.

Remove unnecessary @types/helmet dependency

---

generators/connection/templates/js/mongoose.js
generators/connection/templates/ts/mongoose.ts

```
[INFO] 16:35:47 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.4.4)
info: Feathers application started on http://localhost:3030
(node:33692) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(Use `node --trace-warnings ...` to show where the warning was created)
```
**To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.**

Fix deprecation warning

---

generators/service/templates/ts/hooks.ts

This pull request adds a type definition to the exported hooks created by the generator.
This way, type errors will appear directly in the hooks file instead of in whichever services that tries to use the hooks. It also has the added benefit of enabling better type-hinting for the hooks. 🙌

Improve type-safety of generated hooks object.

---

generators/connection/templates/js/mongodb.js
generators/connection/templates/ts/mongodb.ts

`
(node:2156) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
`

fix error on new mongodb connection

---

generators/service/templates/ts/hooks.ts

https://github.com/feathersjs/generator-feathers/pull/638 was a good change but breaks the codemods that are currently used.
Closes https://github.com/feathersjs/feathers/issues/2503

Fix TypeScript hook export to continue working with codemods
